version: 1.0.0-CI{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  nodejs_version: 8
  npm_key:
    secure: ibHoIgBca+Soq6sDbpcf0KDmNKqBccbvVMTcxSvc3GogObcrWsgkXhQrIo/1lV2o
install:
- ps: Install-Product node $env:nodejs_version
- git submodule update --init --recursive
- cmd: >-
    cd src\dserfozo-rpcbindings

    npm install

    npm run set-buildnum %APPVEYOR_BUILD_NUMBER%

    npm run build

    cd ..\..

    cd tests\DSerfozo.RpcBindings.Node.IntegrationTests

    npm install

    cd ..\..

    nuget update DSerfozo.RpcBindings.Node.sln -Safe -PreRelease

    dotnet restore
build_script:
- cmd: msbuild DSerfozo.RpcBindings.Node.sln /t:Build;Pack /p:Configuration=Release /p:BuildNumber=%APPVEYOR_BUILD_NUMBER% /p:ProjectOutputPath=%cd%\dist
- cmd: cd src\dserfozo-rpcbindings && npm pack
test_script:
- cmd: 'cd src\dserfozo-rpcbindings && npm run test'
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Json.Tests\bin\Release\net461\DSerfozo.RpcBindings.Json.Tests.dll'  
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Node.IntegrationTests\bin\Release\net461\DSerfozo.RpcBindings.Node.IntegrationTests.dll'  
artifacts:
- path: src\DSerfozo.RpcBindings.Json\bin\Release\DSerfozo.RpcBindings.Json*.nupkg
- path: src\dserfozo-rpcbindings\dserfozo-rpcbindings-*.tgz
deploy_script:
- ps: '"registry=https://www.myget.org/F/dserfozo/npm/`r`n//www.myget.org/F/dserfozo/npm/:_authToken=$env:npm_key" | Out-File "$env:userprofile\.npmrc" -Encoding UTF8'
- cd src\dserfozo-rpcbindings
- npm publish
- cd ..\..
- nuget push src\DSerfozo.RpcBindings.Json\bin\Release\DSerfozo.RpcBindings.Json*.nupkg -ApiKey %npm_key% -Source https://www.myget.org/F/dserfozo/api/v2/package